site_name:        Spectra.jl
repo_url:         https://github.com/charlesll/Spectra.jl
site_description: Spectra.jl aims at helping treatment of spectral (Raman, Infrared, XAS, NMR) data under the Julia language
site_author:      charlesll

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md